//
//  FilterList.h
//  GPUIimageCollectionView
//
//  Created by Xavi on 11/5/13.
//  Copyright (c) 2013 Xavier Roman. All rights reserved.
//

#ifndef GPUIimageCollectionView_FilterList_h
#define GPUIimageCollectionView_FilterList_h

typedef enum {
    GPUIMAGE_SATURATION,
    GPUIMAGE_CONTRAST,
    GPUIMAGE_BRIGHTNESS,
    GPUIMAGE_LEVELS,
    GPUIMAGE_EXPOSURE,
    GPUIMAGE_RGB,
    GPUIMAGE_HUE,
    GPUIMAGE_WHITEBALANCE, 
    GPUIMAGE_MONOCHROME,
    GPUIMAGE_FALSECOLOR,
    GPUIMAGE_SHARPEN,
    GPUIMAGE_UNSHARPMASK,
    GPUIMAGE_TRANSFORM,
    GPUIMAGE_TRANSFORM3D,
    GPUIMAGE_CROP,
	//GPUIMAGE_MASK, //needsSecondImage
    GPUIMAGE_GAMMA,
    GPUIMAGE_TONECURVE,
    GPUIMAGE_HIGHLIGHTSHADOW,
    GPUIMAGE_HAZE,
    GPUIMAGE_SEPIA,
    GPUIMAGE_AMATORKA,
    GPUIMAGE_MISSETIKATE,  
    GPUIMAGE_SOFTELEGANCE,
    GPUIMAGE_COLORINVERT,
    GPUIMAGE_GRAYSCALE,
    GPUIMAGE_HISTOGRAM,
    //GPUIMAGE_AVERAGECOLOR, //iPad 2 crash
    //GPUIMAGE_LUMINOSITY, //iPad 2 crash
    GPUIMAGE_THRESHOLD,
    GPUIMAGE_ADAPTIVETHRESHOLD,
    GPUIMAGE_AVERAGELUMINANCETHRESHOLD,
    GPUIMAGE_PIXELLATE,
    GPUIMAGE_POLARPIXELLATE,
    GPUIMAGE_PIXELLATE_POSITION,
    GPUIMAGE_POLKADOT,
    GPUIMAGE_HALFTONE,
    GPUIMAGE_CROSSHATCH,
    GPUIMAGE_SOBELEDGEDETECTION,
    GPUIMAGE_PREWITTEDGEDETECTION,
    GPUIMAGE_CANNYEDGEDETECTION,
    GPUIMAGE_THRESHOLDEDGEDETECTION,
    GPUIMAGE_XYGRADIENT,
//    GPUIMAGE_HARRISCORNERDETECTION, //Logs Processing time, comment for now
//    GPUIMAGE_NOBLECORNERDETECTION,  //Logs Processing time, comment for now
//    GPUIMAGE_SHITOMASIFEATUREDETECTION,//Logs Processing time, comment for now
    GPUIMAGE_HOUGHTRANSFORMLINEDETECTOR,
    //GPUIMAGE_BUFFER, //iPad 2 crash
    //GPUIMAGE_LOWPASS, //iPad 2 crash
    //GPUIMAGE_HIGHPASS,//iPad 2 crash
    //GPUIMAGE_MOTIONDETECTOR, //camera required
    GPUIMAGE_SKETCH,
    GPUIMAGE_THRESHOLDSKETCH,
    GPUIMAGE_TOON,
    GPUIMAGE_SMOOTHTOON,
    GPUIMAGE_TILTSHIFT,
    GPUIMAGE_CGA,
    GPUIMAGE_POSTERIZE,
    GPUIMAGE_CONVOLUTION,
    GPUIMAGE_EMBOSS,
    //GPUIMAGE_LAPLACIAN, //UNKNOWN FILTER
    //GPUIMAGE_CHROMAKEYNONBLEND, //needsSecondImage
    GPUIMAGE_KUWAHARA,
    GPUIMAGE_KUWAHARARADIUS3,
    GPUIMAGE_VIGNETTE,
    GPUIMAGE_GAUSSIAN,
    GPUIMAGE_GAUSSIAN_SELECTIVE,
    GPUIMAGE_GAUSSIAN_POSITION,
    GPUIMAGE_FASTBLUR,
    GPUIMAGE_BOXBLUR,
    GPUIMAGE_MEDIAN,
    GPUIMAGE_BILATERAL,
    GPUIMAGE_MOTIONBLUR,
    GPUIMAGE_ZOOMBLUR,
    GPUIMAGE_SWIRL,
    GPUIMAGE_BULGE,
    GPUIMAGE_PINCH,
    GPUIMAGE_SPHEREREFRACTION,
    GPUIMAGE_GLASSSPHERE,
    GPUIMAGE_STRETCH,
    GPUIMAGE_DILATION,
    GPUIMAGE_EROSION,
    GPUIMAGE_OPENING,
    GPUIMAGE_CLOSING,
    GPUIMAGE_PERLINNOISE,
    //GPUIMAGE_VORONOI, //camera
    GPUIMAGE_MOSAIC,
    GPUIMAGE_LOCALBINARYPATTERN,
//    GPUIMAGE_DISSOLVE, //needsSecondImage
//    GPUIMAGE_CHROMAKEY, //needsSecondImage
//    GPUIMAGE_ADD, //needsSecondImage
//    GPUIMAGE_DIVIDE, //needsSecondImage
//    GPUIMAGE_MULTIPLY, //needsSecondImage
//    GPUIMAGE_OVERLAY, //needsSecondImage
//    GPUIMAGE_LIGHTEN, //needsSecondImage
//    GPUIMAGE_DARKEN, //needsSecondImage
//    GPUIMAGE_COLORBURN, //needsSecondImage
//    GPUIMAGE_COLORDODGE, //needsSecondImage
//    GPUIMAGE_LINEARBURN, //needsSecondImage
//    GPUIMAGE_SCREENBLEND, //needsSecondImage
//    GPUIMAGE_DIFFERENCEBLEND, //needsSecondImage
//    GPUIMAGE_SUBTRACTBLEND, //needsSecondImage
//    GPUIMAGE_EXCLUSIONBLEND,
//    GPUIMAGE_HARDLIGHTBLEND, //needsSecondImage
//    GPUIMAGE_SOFTLIGHTBLEND, //needsSecondImage
//    GPUIMAGE_COLORBLEND, //needsSecondImage
//    GPUIMAGE_HUEBLEND, //needsSecondImage
//    GPUIMAGE_SATURATIONBLEND, //needsSecondImage
//    GPUIMAGE_LUMINOSITYBLEND, //needsSecondImage
//    GPUIMAGE_NORMALBLEND, //needsSecondImage
//    GPUIMAGE_POISSONBLEND, //needsSecondImage
//    GPUIMAGE_OPACITY, //needsSecondImage
//    GPUIMAGE_CUSTOM, //needs shader file
//    GPUIMAGE_UIELEMENT, //just sepia filter
//    GPUIMAGE_FILECONFIG, //not applicable here
//    GPUIMAGE_FILTERGROUP, //group, comment for now
//    GPUIMAGE_FACES, //faces detection, camera
    GPUIMAGE_NUMFILTERS
} GPUImageShowcaseFilterType;

//typedef enum {
//    //GPUIMAGE_SOFTELEGANCE = 500
//
//} GPUImageNoForIpad2;

#endif
